cc_library(
    name = "libdoipcommon",
    srcs = glob(["src/*.cpp"]),
    hdrs = glob(["include/*.h"]),
    includes = [
        "./src",
        "./include",
    ],
    visibility = ["//visibility:public"],
)
