cc_library(
    name = "libdoipclient",
    srcs = ["src/DoIPClient.cpp"],
    hdrs = ["include/DoIPClient_h.h"],
    includes = [
        "./include",
        "./src",
    ],
    visibility = ["//visibility:public"],
    deps = ["//libdoip/libdoipcommon"],
)